name: CI

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: wzshiming/action-sync-hosts@v1
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DNS: 8.8.8.8
          DOMAINS: |
            alive.github.com
            api.github.com
            assets-cdn.github.com
            central.github.com
            codeload.github.com
            ghcr.io
            gist.github.com
            github-cloud.s3.amazonaws.com
            github-com.s3.amazonaws.com
            github-production-release-asset-2e65be.s3.amazonaws.com
            github-production-repository-file-5c1aeb.s3.amazonaws.com
            github-production-user-asset-6210df.s3.amazonaws.com
            github.blog
            github.com
            github.community
            github.githubassets.com
            github.global.ssl.fastly.net
            github.io
            github.map.fastly.net
            githubstatus.com
            live.github.com
            *.github.com
            *.github.io
            *.githubusercontent.com
